### ISSUE TITLE
can this support 2captcha?

### ISSUE THREAD

**Issue by WSrujan** [masterking32/twitch-account-creator#1]

**Comment by masterking32** [comment]
For now, no, You can just anti-captcha.

**Comment by Drabmarker1** [comment]
> For now, no, You can just use anti-captcha.

This should not be too hard for you because 2captcha already gives you the necessary "stuff" to get started https://2captcha.com/p/funcaptcha

**Comment by masterking32** [comment]
I don't have an account there to test. so you need to switch the website. xD

**Comment by WaltDisneyWorld** [comment]
It’s much easier in my opinion to use 2captcha…

**Comment by Drabmarker1** [comment]
And cheaper

**Comment by WaltDisneyWorld** [comment]
Yep.

**Comment by masterking32** [comment]
Ok, I will check it later.

**Comment by WaltDisneyWorld** [comment]
Add me on discord Caleb.#4529

**Comment by Drabmarker1** [comment]
> Ok, I will check it later.

ok

**Comment by joeyc00l** [comment]
hey did anyone impliment this? has someone come up with the code?

**Comment by Anydex** [comment]
you guys are stupid, there are examples of code literally on the 2captcha docs and 2captcha gets the captcha wrong on nearly every single time

**Comment by WaltDisneyWorld** [comment]
I disagree.

**Comment by Anydex** [comment]
You skids cant code for shit, the required code is literally on their site😂

**Comment by masterking32** [comment]
Now project supports 2Captcha and Anti-Captcha.

**Comment by ThiagoBauken** [comment]
https://capmonster.cloud/pt-br/
can support this one?
