### ISSUE TITLE
WORKING ?

### ISSUE THREAD

**Issue by Bulli77** [masterking32/twitch-account-creator#10]
after start i try create account and work and stop before save results i use anti-captcha.

D:\Virtual Machine\NODJE\twitch-account-creator-main\twitch-account-creator-main>node main.js
Username?
lzihdf234
Username: lzihdf234 Password:MJnFQPasfC_MK32 BDay: 1970/7/12
Getting email
Solving captcha
Generating payload
Registering account
Please complete the CAPTCHA correctly.
Username?
asdasds
Username: asdasds Password:CtWzpdLhTx_MK32 BDay: 1980/2/10
Getting email
Solving captcha
Generating payload
Registering account
This username already exists.
Username?
123asdadas22
Username: 123asdadas22 Password:kuFZamWkMf_MK32 BDay: 1974/4/26
Getting email
Solving captcha
Generating payload
Registering account
**Please complete the CAPTCHA correctly.**
Username?

**Comment by NatNyt** [comment]
Working But You Renew File anti-cpatcha.js replace client-api.arkoselabs.com with twitch-api.arkoselabs.com but can work 70 %

**Comment by Bulli77** [comment]
thx :)

**Comment by WhZzi** [comment]
> Working But You Renew File anti-cpatcha.js replace client-api.arkoselabs.com with twitch-api.arkoselabs.com but can work 70 %

Still working in this method?

**Comment by masterking32** [comment]
Solved.
