### ISSUE TITLE
Invalid Captcha

### ISSUE THREAD

**Issue by Drabmarker1** [masterking32/twitch-account-creator#2]
The captcha does not get solved

**Comment by masterking32** [comment]
Did you put your anti-captcha API key in anti-captcha.js?

**Comment by Drabmarker1** [comment]
Yes. and if you're wondering, I also have balance on it.

**Comment by masterking32** [comment]
I check that yesterday, now it's working but there are some issues with verifying accounts. I will check it later. (I made this project 1 year ago and now there are some changes on Twitch.)

**Comment by Herostere** [comment]
I have the same issue, it is stuck on "solving captcha".

> I check that yesterday, now it's working but there are some issues with verifying accounts. I will check it later. (I made this project 1 year ago and now there are some changes on Twitch.)

Thank you for checking it! Appreciate it

**Comment by Drabmarker1** [comment]
> I check that yesterday, now it's working but there are some issues with verifying accounts. I will check it later. (I made this project 1 year ago and now there are some changes on Twitch.)
Thank you :)

**Comment by Drabmarker1** [comment]
> I check that yesterday, now it's working but there are some issues with verifying accounts. I will check it later. (I made this project 1 year ago and now there are some changes on Twitch.)


 Thank you:)

**Comment by masterking32** [comment]
Ok, It's done. I already tested it and working fine.

**Comment by masterking32** [comment]
Ok, now I should close this issue.
The project has already been tested, check this: [VIDEO](https://www.youtube.com/watch?v=fC2KgnYoETw)
