### ISSUE TITLE
Client-Integrity error

### ISSUE THREAD

**Issue by Lucifer192192** [masterking32/twitch-account-creator#22]
Client-Integrity error
Have failed
{"client_id":"kimne78kx3ncx6brgo4mv6wki5h1ko","client_ip":"X.X.X.X","device_id":"XXXXXXXXX","exp":"2022-10-01T05:28:59Z","iat":"2022-09-30T21:28:59Z","is_bad_bot":"true","iss":"Twitch Client Integrity","nbf":"2022-09-30T21:28:59Z","user_id":"XXXXXXXXXX"}

"is_bad_bot":"true

in the follow.js

**Comment by Lucifer192192** [comment]
POST https://gql.twitch.tv/integrity HTTP/1.1
Host: gql.twitch.tv
Connection: keep-alive
Content-Length: 0
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="92"
DNT: 1
x-kpsdk-cd: {"workTime":1664573203325,"id":"9d8a190ed5bbfbdd445ebb8399621691","answers":[4,5],"duration":2.1,"d":1952,"st":1664573203353,"rst":1664573205275}
x-kpsdk-ct: 07w3MfsY6GuwRBFXmZwjmfdaeOMe1IRhrxtxPO1impGDMz6tZ46snqPJ0PBJF24p5lhOx3P1nDHArrgg0vwPx9S7D1eVcslgP9s3kXXAHV6VAIMJ6IlAMZSWceQwUsS4nwF62H9EtMOh4wT4TC4ttz1V

this
x-kpsdk-cd
and this
x-kpsdk-ct

**Comment by masterking32** [comment]
Duplicate:
https://github.com/masterking32/twitch-account-creator/issues/21

**Comment by OxynDev** [comment]
![image-8.png](https://user-images.githubusercontent.com/98268537/229110285-fe143c98-8f5d-4b68-9b07-e5d75ef88a90.png)

UwU
