### ISSUE TITLE
Question:  Are there any sites similar to 1-Sec Mail? Temporary Email Solution API Alternative.

### ISSUE THREAD

**Issue by tariqazmat101** [masterking32/twitch-account-creator#28]
Hello just wanted to know if there is any site similar to that. I don't mind if it's subscription based. 
Also, sincere apologies as this isn't an issue but a general question.

**Comment by masterking32** [comment]
Hello,
I didn't pay for something like that.

- You can make a website like that with your domain and server. (Maybe you can find sources here (I didn't check them): https://github.com/topics/disposable-email)

Some websites:
- https://tempmail.lol/custom.html
- https://temp-mail.io/en/subscription
- https://smailpro.com/pricing
- https://temp-mail.org/en/premium/login
I don't know anything about these websites, I share my search results.

**Comment by tariqazmat101** [comment]
Thank you, I'll close this.
