### ISSUE TITLE
unable to get kasada

### ISSUE THREAD

**Issue by rikutatarin** [masterking32/twitch-account-creator#33]
after the proccess of getting twitch cookies,
it says like:
`"unable to get kasada
unable to get kasada
unable to get kasada
unable to get kasada
unable to get kasada
unable to get kasada
`

**Comment by masterking32** [comment]
Check your CapSolver API key / Balance and proxies.

**Comment by Asp3cTy** [comment]
Im checkin it and continue.. can I help?
