### ISSUE TITLE
not creating accounts with choosen names

### ISSUE THREAD

**Issue by eugenee93** [masterking32/twitch-account-creator#37]
Hi, if I select to choose usernames i get stucked in the step waiting for the verification mail. See the screenshot below.
With random names everything works fine, so it isn´t a capcha or proxy problem I think.

![image](https://user-images.githubusercontent.com/46093445/233734519-732c5ff3-01af-4ae3-a81e-68171ea30819.png)

**Comment by masterking32** [comment]
Check [1secmail](https://www.1secmail.com/) to see do you have access to the website on the server or PC.

**Comment by eugenee93** [comment]
Hi, 1secmail works fine on PC. Strange it works with random usernames and not with choosen names.

**Comment by eugenee93** [comment]
I think I got the error. You can´t choose capital letters in the username.
