### ISSUE TITLE
 random usernames

### ISSUE THREAD

**Issue by ZelloxTV** [masterking32/twitch-account-creator#6]
can you please set it up to generate usernames?

**Comment by joeyc00l** [comment]
hey can you publish the code?

**Comment by vnboy93** [comment]
> all good i coded it myself

can you share? thank you

**Comment by ZelloxTV** [comment]
> > all good i coded it myself
> 
> can you share? thank you


okay tomorrow

**Comment by vnboy93** [comment]
> > > all good i coded it myself
> > 
> > 
> > can you share? thank you
> 
> okay tomorrow

wait mate

**Comment by masterking32** [comment]
Change this to true, https://github.com/masterking32/twitch-account-creator/blob/f2f27f41894c46f6218274da7af66767bc35c9c8/main.js#L18
