### ISSUE TITLE
Captchas not being complete

### ISSUE THREAD

**Issue by WeLoveGaming** [masterking32/twitch-account-creator#8]
```
Username?
TestUsername121
Username: TestUsername121 Password:WenEwiHski_MK32 BDay: 1971/6/12
Getting email
Solving captcha
Generating payload
Registering account
Please complete the CAPTCHA correctly.
```
Thats what happens when I try to run it. I checked Anti-Captcha.com and I was charged for it as well.

**Comment by Roro0752** [comment]
Me too

**Comment by joeyc00l** [comment]
yeah the people at anti-captcha are bad and we have to pay for it its better to use 2captcha but we need to find a code for it

**Comment by Anydex** [comment]
> yeah the people at anti-captcha are bad and we have to pay for it its better to use 2captcha but we need to find a code for it

The service anti-captcha is not bad at all, the success rates from anti-captcha are much higher than 2captcha. Get a grip skid, 2captcha provides all of the code necessary to do it on your own😂

**Comment by Martial4034** [comment]
try to manage your api setup, increase your offers or make confirmations by many workers (3 or 4 )

**Comment by masterking32** [comment]
Solved.
